enum Phase{
  INIT,
  INPUT_WAIT, 
  START,
  SELECT_QUERY,
  HIGHLIGHT_QUERY,
  UNHIGHLIGHT_QUERY,
  SELECT_NEIGHBOR,
  DRAW_LINE,
  CALCULATE_DISTANCE,
  CLEAR_DISTANCE,
  REPORT_CLOSEST_NEIGHBORS
}
